[package]
name = "cri"
version = "0.1.0"
authors = [
    "Mrunal Patel <mrunalp@gmail.com>",
    "Sascha Grunert <mail@saschagrunert.de>",
]
edition = "2018"
description = "Kubernetes Container Runtime Interface implementation"
documentation = "https://docs.rs/cri"
readme = "README.md"
homepage = "https://github.com/cri-o/cri"
repository = "https://github.com/cri-o/cri"
license = "Apache-2.0"
keywords = ["kubernetes", "cri"]
categories = ["network-programming", "api-bindings"]

[[bin]] # Bin to run the HelloWorld gRPC server
name = "criserver"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.32"
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"] }
derive_builder = "0.9.0"
env_logger = "0.7.1"
futures-util = "0.3.5"
getset = "0.1.1"
log = { version = "0.4.11", features = ["serde", "std"] }
prost = "0.6.1"
serde = { version = "1.0.115", features = ["derive"] }
tokio = { version = "0.2.22", features = ["fs", "macros", "stream", "uds"] }
tonic = "0.3.1"

[build-dependencies]
anyhow = "1.0.32"
tonic-build = "0.3.1"

[dev-dependencies]
tokio-test = "0.2.1"
